# [build]
# builder = "dockerfile"
# dockerfile = "Dockerfile"

# [deploy]
# startCommand = "$env:NEXT_PRIVATE_DEV_SERVER_TYPE="webpack"; npm run dev --prefix web-next"

[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "$env:NEXT_PRIVATE_DEV_SERVER_TYPE="webpack"; npm run dev --prefix web-next"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "bot-defender"
