# [build]
# builder = "dockerfile"
# dockerfile = "Dockerfile"

# [deploy]
# startCommand = "npm run build && npm start"

[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "bot-defender"