# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bot-defender"
client_id = "f38307ff28448bc1858ad9f3c2d19baf"
application_url = "https://1670883ec8c0.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"
address = "https://1670883ec8c0.ngrok-free.app/webhooks"
topics = ["app/uninstalled", "shop/update"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Add required scopes
scopes = "read_products,write_products"


 


[auth]
redirect_urls = [ "https://1670883ec8c0.ngrok-free.app/auth/callback" ]

[pos]
embedded = false
