# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Bot Defender"
client_id = "YOUR_CLIENT_ID"
application_url = "https://bot-defender-ts-production.up.railway.app"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"
address = "https://bot-defender-ts-production.up.railway.app/webhooks"
topics = ["app/uninstalled", "shop/update"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Add required scopes
scopes = [
  "read_products",
  "write_products",
  "read_orders",
  "write_orders",
  "read_customers",
  "write_customers",
  "read_script_tags",
  "write_script_tags"
]

[auth]
redirect_urls = [ "https://bot-defender-ts-production.up.railway.app/auth/callback" ]

[pos]
embedded = false
